// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'amz';
  static const String PROJECT_VERSION = '1.1.1';
  static const String LAUNCHERE_ICON = 'assets/icons/launchere_icon.png';
  static const String DD = 'assets/images/dd.png';
  static const String LAUNCHER_ICON = 'assets/images/launcher_icon.png';
  static const String SPLACHSCREEN_IMAGE = 'assets/images/splachscreen_image.png';
}
